### ISSUE TITLE
Add MenuDrivenAreaPer 

### ISSUE THREAD

**Issue by yashlamba** [ricksanc/cpp-programs#4]
Make a Program that has couple of menus. 

First Menu is Select Shape: 

1. Circle
2. Rectangle
3. Square
4. Triangle

followed by second menu that has the option of **Area or Perimeter.**

It takes inputs like radius, length and breadth as per above and displays results.

**Comment by ricksanc** [comment]
Completed the issue AddMenuDrivenAreaPer#4

**Comment by ricksanc** [comment]
#4
